//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated
// <auto-generated/>
//----------------------------------------------------------

using TMPro;
using UnityEngine;
using Moirai.Atropos;
using Moirai.Atropos.UI;

namespace GameLogic.UI
{
    [DisallowMultipleComponent]
	public partial class StartScreenBinder : UIBindComponent
	{
		#region 变量 [VARIABLES]

		[SerializeField] private TextMeshProUGUI m_TmpInfo;
		public TextMeshProUGUI TmpInfo => m_TmpInfo;

		#endregion
	}

	public partial class StartScreen
	{
		private StartScreenBinder _bindComponent;

		private TextMeshProUGUI _tmpInfo => _bindComponent.TmpInfo;

		protected override void ScriptGenerator()
		{
			_bindComponent = gameObject.GetComponent<StartScreenBinder>();
			if(_bindComponent == null)
			{
				Log.Error($"根物体: {gameObject.name} 缺少组件 StartScreenBinder, 请检查！！！");
				return;
			}
		}
	}
}