// <auto-generated>
//     Generated by LogUtility.LogMethods.tt.
//     Do not modify directly — edit the template and regenerate.
// </auto-generated>

using System;
using System.Diagnostics;
using JetBrains.Annotations;
using UnityEngine;

namespace Moirai.Atropos
{
    public static partial class LogUtility
    {
        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [HideInCallstack]
        public static void Debug(object message)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = message?.ToString() ?? string.Empty;
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [HideInCallstack]
        public static void Debug(string message)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = message ?? string.Empty;
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1>(string format, T1 arg1)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2>(string format, T1 arg1, T2 arg2)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3>(string format, T1 arg1, T2 arg2, T3 arg3)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4, T5>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4, T5, T6>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_DEBUG_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Debug)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            handler.Log(ELogLevel.Debug, msg, null);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [HideInCallstack]
        public static void Info(object message)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = message?.ToString() ?? string.Empty;
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [HideInCallstack]
        public static void Info(string message)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = message ?? string.Empty;
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1>(string format, T1 arg1)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2>(string format, T1 arg1, T2 arg2)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3>(string format, T1 arg1, T2 arg2, T3 arg3)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4, T5>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4, T5, T6>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4, T5, T6, T7>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_INFO_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Info)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            handler.Log(ELogLevel.Info, msg, null);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [HideInCallstack]
        public static void Warning(object message)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = message?.ToString() ?? string.Empty;
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [HideInCallstack]
        public static void Warning(string message)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = message ?? string.Empty;
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1>(string format, T1 arg1)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2>(string format, T1 arg1, T2 arg2)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3>(string format, T1 arg1, T2 arg2, T3 arg3)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4, T5>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4, T5, T6>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_WARNING_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Warning)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            handler.Log(ELogLevel.Warning, msg, null);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [HideInCallstack]
        public static void Error(object message)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = message?.ToString() ?? string.Empty;
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [HideInCallstack]
        public static void Error(string message)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = message ?? string.Empty;
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1>(string format, T1 arg1)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2>(string format, T1 arg1, T2 arg2)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3>(string format, T1 arg1, T2 arg2, T3 arg3)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4, T5>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4, T5, T6>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4, T5, T6, T7>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_ERROR_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Error)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            handler.Log(ELogLevel.Error, msg, null);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [HideInCallstack]
        public static void Fatal(object message)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = message?.ToString() ?? string.Empty;
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [HideInCallstack]
        public static void Fatal(string message)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = message ?? string.Empty;
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1>(string format, T1 arg1)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2>(string format, T1 arg1, T2 arg2)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3>(string format, T1 arg1, T2 arg2, T3 arg3)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4, T5>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4, T5, T6>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
		[Conditional("LOG_ALL")]
		[Conditional("LOG_FATAL_ENABLE")]
		[Conditional("LOG_DEBUG_AND_ABOVE")]
		[Conditional("LOG_INFO_AND_ABOVE")]
		[Conditional("LOG_WARNING_AND_ABOVE")]
		[Conditional("LOG_ERROR_AND_ABOVE")]
		[Conditional("LOG_FATAL_AND_ABOVE")]
        [StringFormatMethod("format")]
        [HideInCallstack]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16)
        {
            var handler = Handler;
            if (!handler.IsEnabled(ELogLevel.Fatal)) return;
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            handler.Log(ELogLevel.Fatal, msg, null);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

    }
}
