using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Moirai.Atropos.SourceGenerators
{
    /// <summary>
    /// 为标记了 [HandlerHost(typeof(THandler))] 的 partial class 生成：
    /// s_Handler 字段、Handler 属性（线程安全 get/set）。
    /// <para>生成的成员均为 static，但类声明沿用源类的修饰符（static 或非 static）。</para>
    /// <para>当 CreateDefaultHandler 方法存在时额外生成 s_DefaultFactory 字段与懒加载路径；
    /// 缺失时 Handler.get 直接抛 InvalidOperationException，由 HandlerHostAnalyzer (MIRAI001) 报告警告。</para>
    /// </summary>
    [Generator]
    public class HandlerHostGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    Constants.AttributeFullyQualifiedName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) =>
                    {
                        var classDecl = (ClassDeclarationSyntax)ctx.TargetNode;
                        var classSymbol = (INamedTypeSymbol)ctx.SemanticModel.GetDeclaredSymbol(classDecl)!;

                        var attr = classSymbol.GetAttributes()
                            .First(a => a.AttributeClass!.ToDisplayString() == Constants.AttributeFullyQualifiedName);
                        var handlerType = (INamedTypeSymbol)attr.ConstructorArguments[0].Value!;

                        var hasCreateDefaultHandler = classSymbol.GetMembers(Constants.CreateDefaultHandlerMethodName)
                            .OfType<IMethodSymbol>()
                            .Any(m => m.IsStatic
                                && !m.IsAbstract
                                && SymbolEqualityComparer.Default.Equals(m.ReturnType, handlerType)
                                && m.Parameters.IsEmpty);

                        return new HandlerHostInfo(
                            classSymbol.Name,
                            classSymbol.ContainingNamespace.ToDisplayString(),
                            handlerType.Name,
                            hasCreateDefaultHandler,
                            classSymbol.IsStatic);
                    });

            context.RegisterSourceOutput(provider, static (spc, info) =>
            {
                spc.AddSource(
                    $"{info.ClassName}.g.cs",
                    GenerateCode(in info));
            });
        }

        private static string GenerateCode(in HandlerHostInfo info)
        {
            var classModifier = info.IsStatic ? "static partial class" : "partial class";

            var sb = new StringBuilder(2048);
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   HandlerHost Source Generator — do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine();
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    {classModifier} {info.ClassName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        private static volatile {info.HandlerTypeName} s_Handler;");
            sb.AppendLine();

            if (info.HasCreateDefaultHandler)
            {
                sb.AppendLine($"        private static Func<{info.HandlerTypeName}> s_DefaultFactory = CreateDefaultHandler;");
                sb.AppendLine();
            }

            sb.AppendLine($"        public static {info.HandlerTypeName} Handler");
            sb.AppendLine("        {");
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            sb.AppendLine("                var handler = s_Handler;");
            sb.AppendLine("                if (handler != null)");
            sb.AppendLine("                {");
            sb.AppendLine("                    return handler;");
            sb.AppendLine("                }");
            sb.AppendLine();

            if (info.HasCreateDefaultHandler)
            {
                sb.AppendLine("                var factory = s_DefaultFactory");
                sb.AppendLine("                    ?? throw new InvalidOperationException(");
                sb.AppendLine($"                        \"HandlerHost: default factory not set for {info.ClassName}.\");");
                sb.AppendLine();
                sb.AppendLine("                var created = factory();");
                sb.AppendLine("                if (Interlocked.CompareExchange(ref s_Handler, created, null) == null)");
                sb.AppendLine("                {");
                sb.AppendLine("                    created.Internal_Init();");
                sb.AppendLine("                }");
            }
            else
            {
                sb.AppendLine($"                throw new InvalidOperationException(");
                sb.AppendLine($"                    \"HandlerHost: '{info.ClassName}' has no CreateDefaultHandler, set Handler manually before use.\");");
            }

            sb.AppendLine();
            sb.AppendLine("                return s_Handler;");
            sb.AppendLine("            }");
            sb.AppendLine("            set");
            sb.AppendLine("            {");
            sb.AppendLine("                if (value == null)");
            sb.AppendLine("                {");
            sb.AppendLine("                    throw new ArgumentNullException(nameof(value));");
            sb.AppendLine("                }");
            sb.AppendLine();
            sb.AppendLine("                value.Internal_Init();");
            sb.AppendLine();
            sb.AppendLine("                var previous = Interlocked.Exchange(ref s_Handler, value);");
            sb.AppendLine("                if (previous != null && !ReferenceEquals(previous, value))");
            sb.AppendLine("                {");
            sb.AppendLine("                    previous.Internal_Shutdown();");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private readonly struct HandlerHostInfo
        {
            public readonly string ClassName;
            public readonly string Namespace;
            public readonly string HandlerTypeName;
            public readonly bool HasCreateDefaultHandler;
            public readonly bool IsStatic;

            public HandlerHostInfo(string className, string @namespace, string handlerTypeName, bool hasCreateDefaultHandler, bool isStatic)
            {
                ClassName = className;
                Namespace = @namespace;
                HandlerTypeName = handlerTypeName;
                HasCreateDefaultHandler = hasCreateDefaultHandler;
                IsStatic = isStatic;
            }
        }
    }
}
