// <auto-generated>
//     Generated by LogUtility.LogMethods.tt.
//     Do not modify directly — edit the template and regenerate.
// </auto-generated>

using JetBrains.Annotations;
using UnityEngine;
using Object = UnityEngine.Object;

namespace Moirai.Atropos
{
    public static partial class LogUtility
    {
        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        public static void Verbose(object message, Object context = null)
        {
            var msg = message?.ToString() ?? string.Empty;
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        public static void Verbose(string message, Object context = null)
        {
            var msg = message ?? string.Empty;
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1>(string format, T1 arg1, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2>(string format, T1 arg1, T2 arg2, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3>(string format, T1 arg1, T2 arg2, T3 arg3, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4, T5>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4, T5, T6>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4, T5, T6, T7>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4, T5, T6, T7, T8>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4, T5, T6, T7, T8, T9>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印最详细级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Verbose<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            Handler.Log(ELogLevel.Verbose, msg, null, context);
            RaiseMessageLogged(ELogLevel.Verbose, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        public static void Debug(object message, Object context = null)
        {
            var msg = message?.ToString() ?? string.Empty;
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        public static void Debug(string message, Object context = null)
        {
            var msg = message ?? string.Empty;
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1>(string format, T1 arg1, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2>(string format, T1 arg1, T2 arg2, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3>(string format, T1 arg1, T2 arg2, T3 arg3, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4, T5>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4, T5, T6>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印调试级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Debug<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            Handler.Log(ELogLevel.Debug, msg, null, context);
            RaiseMessageLogged(ELogLevel.Debug, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        public static void Info(object message, Object context = null)
        {
            var msg = message?.ToString() ?? string.Empty;
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        public static void Info(string message, Object context = null)
        {
            var msg = message ?? string.Empty;
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1>(string format, T1 arg1, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2>(string format, T1 arg1, T2 arg2, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3>(string format, T1 arg1, T2 arg2, T3 arg3, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4, T5>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4, T5, T6>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4, T5, T6, T7>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印信息级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Info<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            Handler.Log(ELogLevel.Info, msg, null, context);
            RaiseMessageLogged(ELogLevel.Info, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        public static void Warning(object message, Object context = null)
        {
            var msg = message?.ToString() ?? string.Empty;
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        public static void Warning(string message, Object context = null)
        {
            var msg = message ?? string.Empty;
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1>(string format, T1 arg1, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2>(string format, T1 arg1, T2 arg2, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3>(string format, T1 arg1, T2 arg2, T3 arg3, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4, T5>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4, T5, T6>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印警告级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Warning<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            Handler.Log(ELogLevel.Warning, msg, null, context);
            RaiseMessageLogged(ELogLevel.Warning, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        public static void Error(object message, Object context = null)
        {
            var msg = message?.ToString() ?? string.Empty;
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        public static void Error(string message, Object context = null)
        {
            var msg = message ?? string.Empty;
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1>(string format, T1 arg1, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2>(string format, T1 arg1, T2 arg2, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3>(string format, T1 arg1, T2 arg2, T3 arg3, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4, T5>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4, T5, T6>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4, T5, T6, T7>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Error<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            Handler.Log(ELogLevel.Error, msg, null, context);
            RaiseMessageLogged(ELogLevel.Error, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        public static void Fatal(object message, Object context = null)
        {
            var msg = message?.ToString() ?? string.Empty;
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        public static void Fatal(string message, Object context = null)
        {
            var msg = message ?? string.Empty;
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1>(string format, T1 arg1, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2>(string format, T1 arg1, T2 arg2, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3>(string format, T1 arg1, T2 arg2, T3 arg3, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4, T5>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4, T5, T6>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

        /// <summary>打印严重错误级别日志。</summary>
        [HideInCallstack]
        [StringFormatMethod("format")]
        public static void Fatal<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(string format, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, Object context = null)
        {
            var msg = StringUtility.Format(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            Handler.Log(ELogLevel.Fatal, msg, null, context);
            RaiseMessageLogged(ELogLevel.Fatal, msg, null);
        }

    }
}
