//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Moirai.Atropos.UI
{
    [DisallowMultipleComponent]
    public partial class UIBindComponent : MonoBehaviour
    {
        [SerializeField] private List<Component> m_Components = new List<Component>();

        public T GetComponent<T>(int index) where T : Component
        {
            if (index < 0 || index >= m_Components.Count)
            {
                Log.Error("索引超出范围");
                return null;
            }
            T c = m_Components[index] as T;

            if (c == null)
            {
                Log.Error($"没有找到对应类型: {typeof(T).FullName}");
                return null;
            }
            return c;
        }
    }
}