using System.Text;

namespace Moirai.Atropos.SourceGenerators
{
    /// <summary>
    /// 各生成器共用的发射辅助。
    /// </summary>
    internal static class EmitHelpers
    {
        /// <summary>
        /// 生成头注释：所有产物同一句署名，便于与手写代码区分。
        /// </summary>
        /// <param name="builder">目标构建器。</param>
        internal static void AppendGeneratedHeader(StringBuilder builder)
        {
            builder.AppendLine("// <auto-generated by UIWindowCodegen />");
        }
    }
}
