using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using Moirai.Atropos.Save;
using UnityEditor;
using UnityEngine;

namespace Moirai.Atropos.Editor.Save
{
    /// <summary>
    /// 存档模式快照导出器（MIRAI400/401 分析器的数据源）：扫描全部 <see cref="SaveDataAttribute"/> 二进制后端类型
    /// （MessagePack/MemoryPack/Protobuf），按分析器同款规则提取成员键序号，写出项目根目录 <c>.SaveSchemaSnapshot</c>。
    /// <para>行格式：<c>类型全限定名|成员名:序号;成员名:序号…</c>（序号 -1 = MessagePack 字符串键模式）。
    /// 快照纳入版本控制后，分析器即可在编译期比对键序重排（MIRAI400）与成员删除缺迁移钩子（MIRAI401）；
    /// 二进制线格式变更前重新导出一次即可推进基线。</para>
    /// </summary>
    public static class SaveSchemaSnapshotExporter
    {
        /// <summary>快照文件名（分析器按文件名匹配附加文件）。</summary>
        private const string SNAPSHOT_FILE_NAME = ".SaveSchemaSnapshot";

        /// <summary>MessagePack [Key] 整型序号特性全名。</summary>
        private const string KEY_ATTRIBUTE_NAME = "MessagePack.KeyAttribute";

        /// <summary>MessagePack [MessagePackObject] 特性全名（构造参数 true = 字符串键模式）。</summary>
        private const string MESSAGE_PACK_OBJECT_ATTRIBUTE_NAME = "MessagePack.MessagePackObjectAttribute";

        /// <summary>MemoryPack [MemoryPackOrder] 特性全名。</summary>
        private const string MEMORY_PACK_ORDER_ATTRIBUTE_NAME = "MemoryPack.MemoryPackOrderAttribute";

        /// <summary>MemoryPack [MemoryPackIgnore] 特性全名。</summary>
        private const string MEMORY_PACK_IGNORE_ATTRIBUTE_NAME = "MemoryPack.MemoryPackIgnoreAttribute";

        /// <summary>protobuf-net [ProtoMember] 特性全名。</summary>
        private const string PROTO_MEMBER_ATTRIBUTE_NAME = "ProtoBuf.ProtoMemberAttribute";

        /// <summary>
        /// 导出模式快照到项目根目录（菜单：Tools/Moirai/Save/Export Schema Snapshot）。
        /// </summary>
        [MenuItem("Tools/Moirai/Save/Export Schema Snapshot", false, 100)]
        public static void Export()
        {
            var lines = new List<string>
            {
                "# Moirai Save schema snapshot — generated by Tools/Moirai/Save/Export Schema Snapshot.",
                "# MIRAI400（键序重排）/ MIRAI401（成员删除缺迁移钩子）分析器数据源；纳入版本控制随模式演进更新。",
                "# Format: TypeFullName|Member:Ordinal;Member:Ordinal…（Ordinal -1 = MessagePack 字符串键模式）",
            };

            int typeCount = 0;
            foreach (Type type in TypeCache.GetTypesWithAttribute<SaveDataAttribute>())
            {
                if (!type.IsClass)
                {
                    continue;
                }

                ESaveBackend backend = ResolveBackend(type);
                if (backend < ESaveBackend.MessagePack || backend > ESaveBackend.Protobuf)
                {
                    continue; // 仅二进制后端受键序契约约束（与分析器一致）
                }

                Dictionary<string, int> members = ExtractMemberKeys(type, backend);
                var line = new StringBuilder(ToSnapshotTypeName(type));
                line.Append('|');
                var sorted = new SortedDictionary<string, int>(members, StringComparer.Ordinal);
                bool first = true;
                foreach (KeyValuePair<string, int> pair in sorted)
                {
                    if (!first)
                    {
                        line.Append(';');
                    }

                    line.Append(pair.Key).Append(':').Append(pair.Value);
                    first = false;
                }

                lines.Add(line.ToString());
                typeCount++;
            }

            // 类型按名排序——快照 diff 只反映真实模式变化
            lines.Sort(3, lines.Count - 3, StringComparer.Ordinal);

            string path = Path.Combine(Path.GetDirectoryName(Application.dataPath), SNAPSHOT_FILE_NAME);
            File.WriteAllText(path, string.Join("\n", lines) + "\n", new UTF8Encoding(false));
            Debug.Log($"[SaveSchemaSnapshotExporter] Exported {typeCount} binary-backend save type(s) to {path}");
        }

        /// <summary>
        /// 解析类型的序列化后端（读 <see cref="SaveDataAttribute.Backend"/> 命名参数；未声明为 Json）。
        /// </summary>
        /// <param name="type">目标类型。</param>
        /// <returns>序列化后端标识。</returns>
        private static ESaveBackend ResolveBackend(Type type)
        {
            foreach (CustomAttributeData attribute in CustomAttributeData.GetCustomAttributes(type))
            {
                if (attribute.AttributeType != typeof(SaveDataAttribute))
                {
                    continue;
                }

                foreach (CustomAttributeNamedArgument namedArgument in attribute.NamedArguments)
                {
                    if (namedArgument.MemberName == nameof(SaveDataAttribute.Backend) && namedArgument.TypedValue.Value is int backendValue)
                    {
                        return (ESaveBackend)backendValue;
                    }
                }
            }

            return ESaveBackend.Json;
        }

        /// <summary>
        /// 提取类型的成员键映射（成员名 → 序号；MessagePack 字符串键模式全部记 -1）——与 SaveSchemaAnalyzer 提取规则逐条对齐。
        /// </summary>
        /// <param name="type">目标类型。</param>
        /// <param name="backend">序列化后端。</param>
        /// <returns>成员键映射。</returns>
        private static Dictionary<string, int> ExtractMemberKeys(Type type, ESaveBackend backend)
        {
            var members = new Dictionary<string, int>(StringComparer.Ordinal);

            if (backend == ESaveBackend.MessagePack && IsMessagePackStringKeyed(type))
            {
                foreach (MemberInfo member in EnumerateDataMembers(type, null))
                {
                    members[member.Name] = -1;
                }

                return members;
            }

            string keyAttributeName;
            switch (backend)
            {
                case ESaveBackend.MessagePack:
                    keyAttributeName = KEY_ATTRIBUTE_NAME;
                    break;
                case ESaveBackend.MemoryPack:
                    keyAttributeName = MEMORY_PACK_ORDER_ATTRIBUTE_NAME;
                    break;
                default:
                    keyAttributeName = PROTO_MEMBER_ATTRIBUTE_NAME;
                    break;
            }

            int implicitIndex = 0;
            foreach (MemberInfo member in EnumerateDataMembers(type, backend == ESaveBackend.MemoryPack ? MEMORY_PACK_IGNORE_ATTRIBUTE_NAME : null))
            {
                int? number = TryGetAttributeIntArgument(member, keyAttributeName);
                if (number.HasValue)
                {
                    members[member.Name] = number.Value;
                }
                else if (backend == ESaveBackend.MemoryPack)
                {
                    // MemoryPack 未显式标注 Order 时按声明序（MetadataToken 序）隐式编号
                    members[member.Name] = implicitIndex;
                }

                implicitIndex++;
            }

            return members;
        }

        /// <summary>
        /// 枚举序列化数据成员（本类声明的实例字段/属性，排除 const 与被忽略成员；按 MetadataToken 序保证确定性）。
        /// </summary>
        /// <param name="type">目标类型。</param>
        /// <param name="ignoreAttributeName">忽略特性全名（<c>null</c> = 不过滤）。</param>
        /// <returns>成员枚举（确定性顺序）。</returns>
        private static IEnumerable<MemberInfo> EnumerateDataMembers(Type type, string ignoreAttributeName)
        {
            const BindingFlags FLAGS = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly;
            var members = new List<MemberInfo>();
            members.AddRange(type.GetFields(FLAGS));
            members.AddRange(type.GetProperties(FLAGS));
            members.Sort(CompareByMetadataToken);
            foreach (MemberInfo member in members)
            {
                if (ignoreAttributeName != null && HasAttribute(member, ignoreAttributeName))
                {
                    continue;
                }

                yield return member;
            }
        }

        /// <summary>
        /// MetadataToken 序比较器（声明序的稳定代理）。
        /// </summary>
        private static int CompareByMetadataToken(MemberInfo left, MemberInfo right)
        {
            return left.MetadataToken.CompareTo(right.MetadataToken);
        }

        /// <summary>
        /// MessagePack 类型是否字符串键模式（[MessagePackObject(true)]）。
        /// </summary>
        private static bool IsMessagePackStringKeyed(Type type)
        {
            foreach (CustomAttributeData attribute in CustomAttributeData.GetCustomAttributes(type))
            {
                if (attribute.AttributeType.FullName == MESSAGE_PACK_OBJECT_ATTRIBUTE_NAME
                    && attribute.ConstructorArguments.Count > 0
                    && attribute.ConstructorArguments[0].Value is bool keyAsPropertyName
                    && keyAsPropertyName)
                {
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// 读取成员特性首个整型构造参数。
        /// </summary>
        private static int? TryGetAttributeIntArgument(MemberInfo member, string attributeName)
        {
            foreach (CustomAttributeData attribute in CustomAttributeData.GetCustomAttributes(member))
            {
                if (attribute.AttributeType.FullName == attributeName
                    && attribute.ConstructorArguments.Count > 0
                    && attribute.ConstructorArguments[0].Value is int number)
                {
                    return number;
                }
            }

            return null;
        }

        /// <summary>
        /// 成员是否标注指定特性（按全名匹配——可选包缺席时安全）。
        /// </summary>
        private static bool HasAttribute(MemberInfo member, string attributeName)
        {
            foreach (CustomAttributeData attribute in CustomAttributeData.GetCustomAttributes(member))
            {
                if (attribute.AttributeType.FullName == attributeName)
                {
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// 快照类型键（命名空间.嵌套链——嵌套类型 '+' 转 '.'，与分析器显示格式一致）。
        /// </summary>
        private static string ToSnapshotTypeName(Type type)
        {
            return type.FullName.Replace('+', '.');
        }
    }
}
