#!/usr/bin/env bash
# 转表唯一入口（也是唯一一份逻辑）。Windows 用 gen.bat，它只负责找到 bash 再调本文件。
#
#   ./gen.sh              # 客户端（等价于 ./gen.sh client）
#   ./gen.sh client       # 常规表 + 多语言代码 + 按语言数据
#   ./gen.sh server       # 服务端表（不含多语言，故不涉及变体）
#   ./gen.sh all          # 客户端 + 服务端
#   ./gen.sh client false # 第2参：lazyload 开关，非 true/空 走默认模板
#
# 所有路径与语言清单都来自同目录的 config.ini；本文件不内嵌任何项目路径。

set -o pipefail

cd "$(dirname "$0")" || exit 1
CONFIG_FILE="config.ini"

TARGET="${1:-client}"
LAZYLOAD="${2:-}"

fail() { echo "[ERROR] $*" >&2; exit 1; }
step() { echo "===== $* ====="; }

[ -f "$CONFIG_FILE" ] || fail "$CONFIG_FILE 不存在（应与 gen.sh 同目录）"

# ---------- 配置读取 ----------
# 分标题只作分组：键名全局唯一，这里直接摊平成 CFG_<KEY>，读到 [xxx] 就跳过。
# 值不做 xargs 修剪：xargs 会把反斜杠当转义吃掉，路径尾部的 \ 会被削掉。
declare -A CFG
while IFS='=' read -r raw_key raw_value || [ -n "${raw_key//[$'\r\n']/}" ]; do
    key="${raw_key%$'\r'}"
    key="${key#"${key%%[![:space:]]*}"}"
    key="${key%"${key##*[![:space:]]}"}"
    [ -z "$key" ] && continue
    case "$key" in
        \#*|\;*|[[]*) continue ;;
    esac
    value="${raw_value%$'\r'}"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    CFG["$key"]="$value"
done < "$CONFIG_FILE"

need() { [ -n "${CFG[$1]:-}" ] || fail "$CONFIG_FILE 缺少键 $1（节 [$2]）"; }

need LUBAN_DLL tools
need CONF luban
need L10N_CONF luban
need DATA_OUTPUT_PATH_CLIENT client
need CODE_OUTPUT_PATH_CLIENT client
need CODE_OUTPUT_PATH_L10N client
need L10N_LANGUAGES l10n

LUBAN="${CFG[LUBAN_DLL]}"
[ -f "$LUBAN" ] || fail "Luban 不存在：$LUBAN（先跑 build-luban，或把编译好的文件放进 Luban/）"

# 可选键：缺失时按空处理，对应参数整条不传
optional_args=()
[ -n "${CFG[PATH_VALIDATOR_ROOT]:-}" ] && optional_args+=(-x "pathValidator.rootDir=${CFG[PATH_VALIDATOR_ROOT]}")

# 模板目录：三趟必须用同一个模板，所以只在这里定一次。
# 目录不存在时一致退回内置模板并显式告警——只让某一趟退回会让多语言类与其余表用不同模板。
case "$LAZYLOAD" in
    ""|true|TRUE|1) TEMPLATE_SUFFIX=LazyLoad ;;
    *)              TEMPLATE_SUFFIX=Default ;;
esac
TEMPLATE_DIR="${CFG[CUSTOM_TEMPLATE_ROOT]:-CustomTemplate/}CustomTemplate_Client_${TEMPLATE_SUFFIX}"
template_args=()
if [ -d "$TEMPLATE_DIR" ]; then
    template_args=(--customTemplateDir "$TEMPLATE_DIR")
else
    echo "[WARN] 模板目录不存在：$TEMPLATE_DIR"
    echo "[WARN] 三趟统一使用内置模板（--customTemplateDir 未传）"
fi

# 语言清单：唯一真源，空格分隔
read -r -a LANGUAGES <<< "${CFG[L10N_LANGUAGES]}"
[ "${#LANGUAGES[@]}" -gt 0 ] || fail "L10N_LANGUAGES 为空，拒绝生成一个没有语言变体的 schema"
for lang in "${LANGUAGES[@]}"; do
    seen=0
    for other in "${LANGUAGES[@]}"; do [ "$other" = "$lang" ] && seen=$((seen + 1)); done
    [ "$seen" -le 1 ] || fail "L10N_LANGUAGES 有重复语言码：$lang"
done
BEAN_FIELD="${CFG[L10N_BEAN_FIELD]:-text}"
VARIANTS="$(IFS=,; echo "${LANGUAGES[*]}")"

# ---------- 阶段 ----------
copy_runtime_scripts() {
    local pair src_key dst_key src dst
    for pair in "CONFIG_SCRIPT_SOURCE CONFIG_SCRIPT_TARGET" \
                "CONFIGINIT_SCRIPT_SOURCE CONFIGINIT_SCRIPT_TARGET" \
                "EXTERNALTYPEUTIL_SCRIPT_SOURCE EXTERNALTYPEUTIL_SCRIPT_TARGET"; do
        src_key="${pair%% *}"; dst_key="${pair#* }"
        src="${CFG[$src_key]:-}"; dst="${CFG[$dst_key]:-}"
        # 三件都可选：项目不覆盖某个处理器时留空即可，但留了源头就必须存在
        [ -z "$src" ] && [ -z "$dst" ] && continue
        [ -n "$src" ] && [ -n "$dst" ] || fail "$CONFIG_FILE：$src_key 与 $dst_key 要同时给"
        [ -f "$src" ] || fail "$src 不存在"
        mkdir -p "$(dirname "$dst")"
        cp -f "$src" "$dst" || fail "拷贝失败：$src -> $dst"
    done
}

# 由 L10N_LANGUAGES 派生 Luban 用的变体声明 xml。必须在多语言那几趟之前写好。
# 生成器只写 ASCII：无 BOM 的脚本被 PowerShell 按 cp936 解会产出看不懂的解析错误，
# 这里干脆不用 PS，也就没有这件事。
generate_l10n_schema() {
    local xml="${CFG[L10N_SCHEMA_XML]:-Temp/l10n_schema.xml}"

    mkdir -p "$(dirname "$xml")"
    {
        echo '<module name="L10n">'
        echo '    <bean name="LocalizationBean" comment="localized text for one language">'
        echo "        <var name=\"$BEAN_FIELD\" type=\"string\" variants=\"$VARIANTS\"/>"
        echo '    </bean>'
        echo '</module>'
    } > "$xml" || fail "写 $xml 失败"
    echo "[l10n] 变体声明 -> $xml (variants=$VARIANTS)"
}

# 游戏侧自报语言用的 C# 常量。
# ⚠ 必须在常规趟之后调用：常量落在 Luban 的代码输出目录里时，那一趟的代码 saver 会把
# "不属于本次生成范围"的已存在文件当多余项删掉——实测主趟日志出现
# [remove] .../Gen\L10n\L10nLanguages.cs 且退出码仍是 0，先写后跑等于白写。
generate_language_constant() {
    local cs="${CFG[L10N_LANG_LIST_CODE]:-}"
    local ns="${CFG[L10N_LANG_CLASS_NAMESPACE]:-Moirai.GameProto.Config}"

    [ -n "$cs" ] || fail "$CONFIG_FILE 缺少键 L10N_LANG_LIST_CODE（节 [l10n]）"
    mkdir -p "$(dirname "$cs")"
    {
        echo '//------------------------------------------------------------------------------'
        echo '// <auto-generated>'
        echo '//     Generated by gen.sh from L10N_LANGUAGES in config.ini.'
        echo '//     Change the language list there and re-run the export; do not edit by hand.'
        echo '// </auto-generated>'
        echo '//------------------------------------------------------------------------------'
        echo ''
        echo "namespace $ns"
        echo '{'
        echo '    /// <summary>'
        echo '    /// Languages produced by the per-language export passes, in declaration order.'
        echo '    /// Each language data file lives in a subdirectory of the config table root named'
        echo '    /// after the language code; the current language is picked by LocalizationService.'
        echo '    /// </summary>'
        echo '    public static class L10nLanguages'
        echo '    {'
        echo '        public static readonly string[] Codes ='
        echo '        {'
        local i
        for i in "${!LANGUAGES[@]}"; do
            if [ "$i" -lt "$(( ${#LANGUAGES[@]} - 1 ))" ]; then
                echo "            \"${LANGUAGES[$i]}\","
            else
                echo "            \"${LANGUAGES[$i]}\""
            fi
        done
        echo '        };'
        echo '    }'
        echo '}'
    } > "$cs" || fail "写 $cs 失败"
    echo "[l10n] 语言常量 -> $cs"
}

run_client() {
    step "客户端：拷贝运行期处理器"
    copy_runtime_scripts

    step "客户端：派生多语言变体声明 xml"
    generate_l10n_schema

    step "客户端 1/3：常规表（语言无关，一趟出代码与数据）"
    dotnet "$LUBAN" -t client -c cs-bin -d bin --conf "${CFG[CONF]}" \
        "${template_args[@]}" \
        -x code.lineEnding=crlf \
        "${optional_args[@]}" \
        -x "outputCodeDir=${CFG[CODE_OUTPUT_PATH_CLIENT]}" \
        -x "outputDataDir=${CFG[DATA_OUTPUT_PATH_CLIENT]}" \
        || fail "常规趟失败"

    # 多语言代码落在 Gen/L10n/（与主趟同树、分目录）。必须在常规趟之后：常规趟的清理是递归的，
    # 会把 Gen/L10n/ 整个删掉；反过来这一趟的清理只及自己目录，不会碰常规表的类。
    step "客户端 2/3：多语言代码（bean 只剩一个变体字段，代码与语言无关）"
    dotnet "$LUBAN" -t client -c cs-bin --conf "${CFG[L10N_CONF]}" \
        "${template_args[@]}" \
        -x code.lineEnding=crlf \
        "${optional_args[@]}" \
        -x "outputCodeDir=${CFG[CODE_OUTPUT_PATH_L10N]}" \
        || fail "多语言代码趟失败"

    # 一次进程只解析一版变体，所以有几种语言就跑几趟；且必须排在常规趟之后
    # （常规趟的 bin saver 会把输出目录连同语言子目录一起清掉，退出码还是 0）
    local data_root="${CFG[DATA_OUTPUT_PATH_CLIENT]}"
    local lang
    for lang in "${LANGUAGES[@]}"; do
        step "客户端 3/3：按语言导数据 -> ${data_root}${lang}"
        dotnet "$LUBAN" -t client -d bin --conf "${CFG[L10N_CONF]}" \
            "${template_args[@]}" \
            --variant "default=${lang}" \
            "${optional_args[@]}" \
            -x "outputDataDir=${data_root}${lang}" \
            || fail "语言 $lang 的数据趟失败"
    done

    # 所有会清 Gen/ 的趟都跑完了，才写这个落在生成目录里的常量（见函数注释）
    step "客户端：生成运行期语言常量"
    generate_language_constant
}

run_server() {
    [ -n "${CFG[DATA_OUTPUT_PATH_SERVER]:-}" ] || fail "$CONFIG_FILE 缺少键 DATA_OUTPUT_PATH_SERVER（节 [server]）"
    step "服务端：常规表（不含多语言，故不带 --variant）"
    dotnet "$LUBAN" -t server -c cs-bin -d bin --conf "${CFG[CONF]}" \
        -x code.lineEnding=crlf \
        "${optional_args[@]}" \
        -x "outputCodeDir=${CFG[CODE_OUTPUT_PATH_SERVER]}" \
        -x "outputDataDir=${CFG[DATA_OUTPUT_PATH_SERVER]}" \
        || fail "服务端趟失败"
}

case "$TARGET" in
    client) run_client ;;
    server) run_server ;;
    all)    run_client; run_server ;;
    -h|--help|help)
        # 只打印 shebang 之后连续那段注释头，遇到第一行非注释就停
        awk 'NR>1 && /^#/{print; next} NR>1{exit}' "$0"
        exit 0 ;;
    *)      fail "未知目标：$TARGET（可用 client | server | all）" ;;
esac

echo "[OK] 转表完成：$TARGET"
