# 路径使用相对于脚本所在目录的相对路径（推荐），或绝对路径
LUBAN_DLL=.\Luban\Luban.dll
CONF=luban.conf
CUSTOM_TEMPLATE_ROOT=.\CustomTemplate\

PATH_VALIDATOR_ROOT=..\Client\

DATA_OUTPUT_PATH_CLIENT=..\Client\Assets\AssetRaw\Default\Config\Table\
CODE_OUTPUT_PATH_CLIENT=..\Client\Assets\Scripts\GameProto\Gen\

DATA_OUTPUT_PATH_SERVER=..\Server\Config\Table\
CODE_OUTPUT_PATH_SERVER=..\Server\Scripts\Config\Gen\

CONFIG_SCRIPT_SOURCE=.\CustomTemplate\ConfigTableModule.cs
CONFIG_SCRIPT_TARGET=..\Client\Assets\Scripts\GameProto\ConfigTableModule.cs
CONFIGINIT_SCRIPT_SOURCE=.\CustomTemplate\ConfigTableModule_Init.cs
CONFIGINIT_SCRIPT_TARGET=..\Client\Assets\Scripts\GameProto\ConfigTableModule_Init.cs

EXTERNALTYPEUTIL_SCRIPT_SOURCE=.\CustomTemplate\ExternalTypeUtil.cs
EXTERNALTYPEUTIL_SCRIPT_TARGET=..\Client\Assets\Scripts\GameProto\ExternalTypeUtil.cs

L10N_TEXTFILE_PATH=.\Excels\L10n\LocalizedStrings.xlsx
