<#
    Derives every language-dependent artifact from one list (L10N_LANGUAGES in path_define.conf):
      1. the Luban bean declaration carrying the field variants  -> feeds the per-language data passes
      2. the runtime language constant the config handler self-reports with

    Kept ASCII-only on purpose: Windows PowerShell 5.1 decodes a BOM-less .ps1 as the ANSI
    codepage, so non-ASCII literals here would corrupt the emitted files.
    Called by both gen_code_bin_to_project.bat and .sh; the two shell scripts only parse paths.
#>
[CmdletBinding()]
param(
    # Language codes, space or comma separated. Deliberately a single string: with a string[]
    # parameter, the extra elements handed over unquoted by cmd/bash bind positionally to the
    # NEXT parameter (this put 'en' into $Namespace and produced a one-language schema).
    [Parameter(Mandatory = $true)][string] $Languages,
    [string] $BeanField = 'text',
    [string] $SchemaOut = '',
    [string] $LanguageCodeOut = '',
    [string] $Namespace = 'Moirai.GameProto.Config'
)

$ErrorActionPreference = 'Stop'

$clean = @( $Languages -split '[,\s]+' | Where-Object { $_ -ne '' } )
if ($clean.Count -eq 0) {
    Write-Error 'L10N_LANGUAGES is empty; refuse to generate a schema with no language variant.'
}
$duplicated = @($clean | Group-Object | Where-Object { $_.Count -gt 1 } | ForEach-Object { $_.Name })
if ($duplicated.Count -gt 0) {
    Write-Error ("Duplicated language code(s): " + ($duplicated -join ', '))
}

function Write-Utf8Bom([string] $Path, [string] $Text) {
    $dir = Split-Path -Parent $Path
    if ($dir -and -not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }
    [System.IO.File]::WriteAllText($Path, $Text, (New-Object System.Text.UTF8Encoding($true)))
}

if ($SchemaOut) {
    $xml = @(
        '<module name="L10n">'
        '    <bean name="LocalizationBean" comment="localized text for one language">'
        ('        <var name="{0}" type="string" variants="{1}"/>' -f $BeanField, ($clean -join ','))
        '    </bean>'
        '</module>'
    ) -join [Environment]::NewLine
    Write-Utf8Bom $SchemaOut ($xml + [Environment]::NewLine)
    Write-Host ("[l10n] schema  -> " + $SchemaOut)
}

if ($LanguageCodeOut) {
    $codes = ($clean | ForEach-Object { '            "' + $_ + '"' }) -join ",`r`n"
    $cs = @(
        '//------------------------------------------------------------------------------'
        '// <auto-generated>'
        '//     Generated by Tools\gen_l10n_schema.ps1 from L10N_LANGUAGES in path_define.conf.'
        '//     Change the language list there and re-run the export; do not edit by hand.'
        '// </auto-generated>'
        '//------------------------------------------------------------------------------'
        ''
        ('namespace ' + $Namespace)
        '{'
        '    /// <summary>'
        '    /// Languages produced by the per-language export passes, in declaration order.'
        '    /// Each language data file lives in a subdirectory of the config table root named'
        '    /// after the language code; the current language is picked by LocalizationService.'
        '    /// </summary>'
        '    public static class L10nLanguages'
        '    {'
        '        public static readonly string[] Codes ='
        '        {'
        ($codes)
        '        };'
        '    }'
        '}'
    ) -join [Environment]::NewLine
    Write-Utf8Bom $LanguageCodeOut ($cs + [Environment]::NewLine)
    Write-Host ("[l10n] codes   -> " + $LanguageCodeOut)
}
