name: build-release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag you want create. (sample 1.0.0)"
        required: true
      dry-run:
        description: "dry-run: true will never create release/nuget."
        required: true
        default: false
        type: boolean

jobs:
  update-packagejson:
    permissions:
      actions: read
      contents: write
    uses: TeamMoirai/GitHubActions/.github/workflows/update-packagejson.yaml@main
    with:
      file-path: ./package.json
      tag: ${{ inputs.tag }}
      dry-run: ${{ inputs.dry-run }}

#  build-dotnet:
#    needs: [update-packagejson]
#    permissions:
#      contents: read
#    runs-on: ubuntu-24.04
#    timeout-minutes: 10
#    steps:
#      - run: echo ${{ needs.update-packagejson.outputs.sha }}
#      - uses: TeamMoirai/GitHubActions/.github/actions/checkout@main
#        with:
#          ref: ${{ needs.update-packagejson.outputs.sha }}
#      - uses: TeamMoirai/GitHubActions/.github/actions/setup-dotnet@main
#      # build and pack nuget (.nupkg and .symbols.nupkg will be created)
#      - run: dotnet build -c Release -p:Version=${{ inputs.tag }}
#      - run: dotnet test -c Release --no-build
#      - run: dotnet pack ./Moirai.Atropos.csproj -c Release --no-build -p:Version=${{ inputs.tag }} -p:IncludeSymbols=true -o ./publish
#      # Store artifacts.
#      - uses: TeamMoirai/GitHubActions/.github/actions/upload-artifact@main
#        with:
#          name: nuget
#          path: ./publish/
#          retention-days: 1
#
#  build-unity:
#    needs: [update-packagejson]
#    strategy:
#      matrix:
#        unity: ["2022.3.39f1"]
#    permissions:
#      contents: read
#    runs-on: ubuntu-24.04
#    timeout-minutes: 15
#    steps:
#      - run: echo ${{ needs.update-packagejson.outputs.sha }}
#      - uses: TeamMoirai/GitHubActions/.github/actions/checkout@main
#        with:
#          ref: ${{ needs.update-packagejson.outputs.sha }}
#      # Execute scripts: Export Package
#      # /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod PackageExporter.Export
#      - name: Build Unity (.unitypacakge)
#        uses: TeamMoirai/GitHubActions/.github/actions/unity-builder@main
#        env:
#          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
#          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
#        with:
#          projectPath: Sandbox/Unity
#          unityVersion: ${{ matrix.unity }}
#          targetPlatform: StandaloneLinux64
#          buildMethod: PackageExporter.Export
#
#      - uses: TeamMoirai/GitHubActions/.github/actions/check-metas@main # check meta files
#        with:
#          directory: Sandbox/Unity
#
#      # Store artifacts.
#      - uses: TeamMoirai/GitHubActions/.github/actions/upload-artifact@main
#        with:
#          name: com.moirai.framework.${{ inputs.tag }}.unitypackage
#          path: ./Sandbox/Unity/com.moirai.framework.${{ inputs.tag }}.unitypackage
#          retention-days: 1
#
#  # publish
#  publish:
#    name: "Publish NuGet packages"
#    needs: [build-dotnet, build-unity]
#    permissions:
#      contents: read
#      id-token: write # required for NuGet Trusted Publish
#    runs-on: ubuntu-24.04
#    timeout-minutes: 10
#    steps:
#      - uses: TeamMoirai/GitHubActions/.github/actions/setup-dotnet@main
#      - uses: TeamMoirai/GitHubActions/.github/actions/download-artifact@main
#      # push nuget
#      - name: NuGet login (OIDC)
#        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
#        id: login
#        with:
#          user: ${{ secrets.NUGET_USER }}
#      - run: dotnet nuget push "./nuget/*.nupkg" --skip-duplicate -s https://api.nuget.org/v3/index.json -k "${NUGET_KEY}"
#        if: ${{ !inputs.dry-run }}
#        env:
#          NUGET_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}

  # release
  create-release:
    needs: [update-packagejson]
#    needs: [update-packagejson, publish]
    permissions:
      contents: write
      id-token: write # required for NuGet Trusted Publish
    uses: TeamMoirai/GitHubActions/.github/workflows/create-release.yaml@main
    with:
      commit-id: ${{ needs.update-packagejson.outputs.sha }}
      dry-run: ${{ inputs.dry-run }}
      tag: ${{ inputs.tag }}
      nuget-push: false
      release-upload: false
#      release-upload: true
#      release-asset-path: ./com.moirai.framework.${{ inputs.tag }}.unitypackage/com.moirai.framework.${{ inputs.tag }}.unitypackage
    secrets: inherit

  cleanup:
    if: ${{ needs.update-packagejson.outputs.is-branch-created == 'true' }}
    needs: [update-packagejson, create-release]
    permissions:
      contents: write
    uses: TeamMoirai/GitHubActions/.github/workflows/clean-packagejson-branch.yaml@main
    with:
      branch: ${{ needs.update-packagejson.outputs.branch-name }}